package com.github.mwiest.voclet.ui.theme

import androidx.compose.ui.graphics.Color

// Brand orange #F37719 (logo), on cool slate neutrals so the orange reads saturated.
// primary is the logo orange itself and carries a near-black label; white text on an orange
// this bright can never reach 4.5:1, which is why a tonal-palette generator has to darken it
// to a brown. Orange as a *foreground* on a surface is only 2.8:1, so use emberInk for that
// (text buttons, outlined labels, icons) - see ExtendedColorScheme.
// secondary = teal, tertiary = indigo: one warm voice against one cool ramp.

val primaryLight = Color(0xFFF37719)
val onPrimaryLight = Color(0xFF331100)
val primaryContainerLight = Color(0xFFFFDCC5)
val onPrimaryContainerLight = Color(0xFF3A1400)
val secondaryLight = Color(0xFF00697F)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF00A0C4)
val onSecondaryContainerLight = Color(0xFF002A35)
val tertiaryLight = Color(0xFF3D5A9E)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFDBE3FA)
val onTertiaryContainerLight = Color(0xFF16224A)
val errorLight = Color(0xFFC0121B)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF7A0009)
val backgroundLight = Color(0xFFFBFBFE)
val onBackgroundLight = Color(0xFF171A21)
val surfaceLight = Color(0xFFFBFBFE)
val onSurfaceLight = Color(0xFF171A21)
val surfaceVariantLight = Color(0xFFDFE2EC)
val onSurfaceVariantLight = Color(0xFF454A57)
val outlineLight = Color(0xFF767B8A)
val outlineVariantLight = Color(0xFFC6CAD6)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2B2F38)
val inverseOnSurfaceLight = Color(0xFFF1F2F7)
val inversePrimaryLight = Color(0xFFFFB077)
val surfaceDimLight = Color(0xFFDDE0E9)
val surfaceBrightLight = Color(0xFFFFFFFF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF5F6FA)
val surfaceContainerLight = Color(0xFFEFF1F6)
val surfaceContainerHighLight = Color(0xFFE9EBF2)
val surfaceContainerHighestLight = Color(0xFFE2E5EE)

val primaryDark = Color(0xFFFF8A3D)
val onPrimaryDark = Color(0xFF401600)
val primaryContainerDark = Color(0xFF6B2E00)
val onPrimaryContainerDark = Color(0xFFFFDCC5)
val secondaryDark = Color(0xFF6ED3F0)
val onSecondaryDark = Color(0xFF00333F)
val secondaryContainerDark = Color(0xFF006A82)
val onSecondaryContainerDark = Color(0xFFCDF1FF)
val tertiaryDark = Color(0xFFB4C6FF)
val onTertiaryDark = Color(0xFF17284F)
val tertiaryContainerDark = Color(0xFF2F4370)
val onTertiaryContainerDark = Color(0xFFDCE4FF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF10131A)
val onBackgroundDark = Color(0xFFE2E5EE)
val surfaceDark = Color(0xFF10131A)
val onSurfaceDark = Color(0xFFE2E5EE)
val surfaceVariantDark = Color(0xFF414654)
val onSurfaceVariantDark = Color(0xFFC6CAD6)
val outlineDark = Color(0xFF8F94A3)
val outlineVariantDark = Color(0xFF414654)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE2E5EE)
val inverseOnSurfaceDark = Color(0xFF2B2F38)
val inversePrimaryDark = Color(0xFF9C4400)
val surfaceDimDark = Color(0xFF10131A)
val surfaceBrightDark = Color(0xFF363B45)
val surfaceContainerLowestDark = Color(0xFF0A0D12)
val surfaceContainerLowDark = Color(0xFF171A21)
val surfaceContainerDark = Color(0xFF1B1F27)
val surfaceContainerHighDark = Color(0xFF262A33)
val surfaceContainerHighestDark = Color(0xFF31353F)

val successLight = Color(0xFF0E7A4B)
val onSuccessLight = Color(0xFFFFFFFF)
val successContainerLight = Color(0xFFA6EFC4)
val onSuccessContainerLight = Color(0xFF00341D)

val successDark = Color(0xFF7BE0AB)
val onSuccessDark = Color(0xFF00341E)
val successContainerDark = Color(0xFF12603C)
val onSuccessContainerDark = Color(0xFFA5F5C9)

// Orange as a foreground on surfaces, where the vivid primary would fail contrast.
val emberInkLight = Color(0xFF9A4200)
val emberInkDark = Color(0xFFFFB077)
